
set-option -g default-shell /usr/sbin/zsh

# switch main modifier to C_a
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# allows mouse grab for scrolling and panel size change
set -g mouse on

# switch panels with ALT+h/j/k/l (vim like)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# resize panes (alt+arrows) by 5 cols/row
bind -n C-M-Left  resize-pane -L 5
bind -n C-M-Down  resize-pane -D 5
bind -n C-M-Up    resize-pane -U 5
bind -n C-M-Right resize-pane -R 5


# more intuitive split
bind '\' split-window -h
bind '-' split-window -v
unbind '"'
unbind "%"

# bind config reload
bind r source-file ~/.config/tmux/tmux.conf

# floating window & scratchpad
bind j display-popup -E -w 80% -h 80%
bind o display-popup -E -w 80% -h 80% "$EDITOR ~/Documents/$USER/scratchpad.md"

# make popup windows rounded
set -g popup-border-lines "rounded"
